import type { CvLocale, CvSectionType } from '@/types/cv';

export const SECTION_TITLES: Record<CvSectionType, Record<CvLocale, string>> = {
  personal_header: { nl: '', en: '' },
  contact: { nl: 'Contact', en: 'Contact' },
  photo: { nl: 'Foto', en: 'Photo' },
  profile: { nl: 'Profiel', en: 'Profile' },
  experience: { nl: 'Werkervaring', en: 'Work experience' },
  education: { nl: 'Opleiding', en: 'Education' },
  skills: { nl: 'Vaardigheden', en: 'Skills' },
  languages: { nl: 'Talen', en: 'Languages' },
  interests: { nl: 'Interesses', en: 'Interests' },
  extra: { nl: 'Overig', en: 'Other' },
  digital_skills: { nl: 'Digitale vaardigheden', en: 'Digital skills' },
  custom_text: { nl: 'Vrije tekst', en: 'Free text' },
  custom_list: { nl: 'Lijst', en: 'List' },
};

export function getSectionTitle(
  type: CvSectionType,
  locale: CvLocale,
  override?: string
): string {
  if (override?.trim()) return override.trim();
  return SECTION_TITLES[type]?.[locale] ?? type;
}

export const UI_LABELS: Record<CvLocale, Record<string, string>> = {
  nl: {
    add: 'Toevoegen',
    remove: 'Verwijderen',
    addSection: 'Sectie toevoegen',
    structure: 'Structuur',
    localeNl: 'Nederlands',
    localeEn: 'Engels',
    generateEn: 'Genereer Engels',
    aiFill: 'AI vullen',
    aiPolish: 'AI polijsten',
    exportNl: 'Exporteer NL',
    exportEn: 'Exporteer EN',
    hidden: 'Verborgen',
    subsection: 'Subsectie',
    layoutFull: 'Volledige breedte',
    layoutHalf: 'Halve kolom',
    layoutSidebar: 'Zijbalk',
    layoutMain: 'Hoofdkolom',
    layoutTwoColumn: 'Twee kolommen',
    layoutGrid3: 'Drie kolommen',
    templateChangeConfirm: 'Template wijzigen reset de sectie-indeling. Doorgaan?',
    name: 'Naam',
    title: 'Functietitel',
    phone: 'Telefoon',
    email: 'E-mail',
    location: 'Plaats',
    profilePlaceholder: 'Korte profieltekst…',
    extraPlaceholder: 'Rijbewijs, beschikbaarheid, …',
    role: 'Functie',
    organization: 'Organisatie',
    period: 'Periode',
    description: 'Omschrijving',
    institution: 'Instelling / opleiding',
    diploma: 'Diploma / richting',
    language: 'Taal',
    level: 'Niveau',
    digitalSkillsPlaceholder: 'PC-vaardigheden…',
  },
  en: {
    add: 'Add',
    remove: 'Remove',
    addSection: 'Add section',
    structure: 'Structure',
    localeNl: 'Dutch',
    localeEn: 'English',
    generateEn: 'Generate English',
    aiFill: 'AI fill',
    aiPolish: 'AI polish',
    exportNl: 'Export NL',
    exportEn: 'Export EN',
    hidden: 'Hidden',
    subsection: 'Subsection',
    layoutFull: 'Full width',
    layoutHalf: 'Half column',
    layoutSidebar: 'Sidebar',
    layoutMain: 'Main column',
    layoutTwoColumn: 'Two columns',
    layoutGrid3: 'Three columns',
    templateChangeConfirm: 'Changing template resets section layout. Continue?',
    name: 'Name',
    title: 'Job title',
    phone: 'Phone',
    email: 'Email',
    location: 'Location',
    profilePlaceholder: 'Short profile text…',
    extraPlaceholder: 'Driving licence, availability, …',
    role: 'Role',
    organization: 'Organization',
    period: 'Period',
    description: 'Description',
    institution: 'Institution / education',
    diploma: 'Diploma / field',
    language: 'Language',
    level: 'Level',
    digitalSkillsPlaceholder: 'Computer skills…',
  },
};

export function uiLabel(locale: CvLocale, key: string): string {
  return UI_LABELS[locale][key] ?? key;
}
